FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci

# Copy .env file if it exists, or use build args
ARG REACT_APP_AZURE_MAPS_SUBSCRIPTION_KEY
ARG REACT_APP_GH_LONG
ARG REACT_APP_GH_LAT
ARG REACT_APP_IG_LONG
ARG REACT_APP_IG_LAT
ARG REACT_APP_CK_LONG
ARG REACT_APP_CK_LAT
ARG REACT_APP_CANOPY_LAT
ARG REACT_APP_CANOPY_LONG
ARG REACT_APP_MARRIOTT_LAT
ARG REACT_APP_MARRIOTT_LONG
ARG REACT_APP_PASSCODE
ARG REACT_APP_BACKEND_URL

ENV REACT_APP_AZURE_MAPS_SUBSCRIPTION_KEY=$REACT_APP_AZURE_MAPS_SUBSCRIPTION_KEY
ENV REACT_APP_GH_LONG=$REACT_APP_GH_LONG
ENV REACT_APP_GH_LAT=$REACT_APP_GH_LAT
ENV REACT_APP_IG_LONG=$REACT_APP_IG_LONG
ENV REACT_APP_IG_LAT=$REACT_APP_IG_LAT
ENV REACT_APP_CK_LONG=$REACT_APP_CK_LONG
ENV REACT_APP_CK_LAT=$REACT_APP_CK_LAT
ENV REACT_APP_CANOPY_LAT=$REACT_APP_CANOPY_LAT
ENV REACT_APP_CANOPY_LONG=$REACT_APP_CANOPY_LONG
ENV REACT_APP_MARRIOTT_LAT=$REACT_APP_MARRIOTT_LAT
ENV REACT_APP_MARRIOTT_LONG=$REACT_APP_MARRIOTT_LONG
ENV REACT_APP_PASSCODE=$REACT_APP_PASSCODE
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL

COPY . .
RUN npm run build
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN echo 'server { \
    listen 80; \
    server_name localhost; \
    root /usr/share/nginx/html; \
    index index.html; \
    location / { \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

